feign:
  client:
    config:
      financial-analysis-api:
        read-timeout: ${FINANCIAL_ANALYSIS_READ_TIMEOUT_MS:100}
        connect-timeout: ${FINANCIAL_ANALYSIS_CONNECT_TIMEOUT_MS:100}
        server-url: ${FINANCIAL_ANALYSIS_SERVER_URL}
        health-endpoint: ${FINANCIAL_ANALYSIS_HEALTH_ENDPOINT}
        endpoint: ${FINANCIAL_ANALYSIS_ENDPOINT}
      credit-card-api:
        read-timeout: ${CREDIT_CARD_READ_TIMEOUT_MS:100}
        connect-timeout: ${CREDIT_CARD_CONNECT_TIMEOUT_MS:100}
        server-url: ${CREDIT_CARD_SERVER_URL}
        health-endpoint: ${CREDIT_CARD_HEALTH_ENDPOINT}
        request-endpoint: ${CREDIT_CARD_REQUEST_ENDPOINT}
        block-endpoint: ${CREDIT_CARD_BLOCK_ENDPOINT}

schedule:
  fixed-delay:
    credit-cards-linker: ${CREDIT_CARDS_LINKER_FIXED_DELAY_MS:60000}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      app: ${APP_NAME:proposal}
      env: ${ENVIRONMENT:dev}
  endpoints:
    web:
      cors:
        allowed-methods: GET
        allowed-origins: ${MANAGEMENT_ALLOWED_ORIGINS}
      exposure:
        include: health, prometheus

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_SCHEMA}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:}  # defaults to empty
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
      javax:
        persistence:
          query:
            timeout: ${PERSISTENCE_QUERY_TIMEOUT_MS:50}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_JWT_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}

logging:
  level:
    root: ${LOG_LEVEL:WARN}
