feign:
  client:
    config:
      financial-analysis:
        read-timeout: 100
        connect-timeout: 100
        url: ${FINANCIAL_ANALYSIS_URL}

spring:
  jpa:
    properties:
      javax:
        persistence:
          query:
            timeout: 50
      hibernate:
        dialect=org:
          hibernate:
            dialect: MariaDB103Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:}  # defaults to empty
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_SCHEMA}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
